/**
 * Created by MD.ImdadulHuq on 17-Aug-17.
 */
/** @constant
 @type {string}
 */

module.exports = {
    PUSH_MOVIE_RATED:'PUSH_MOVIE_RATED',
    PUSH_MOVIE_ADDED:'PUSH_MOVIE_ADDED',
    PUSH_MOVIE_EDITED:'PUSH_MOVIE_EDITED',
    PUSH_MOVIE_DELETED:'PUSH_MOVIE_DELETED',

    INVALID_LOGIN_DETAILS:'INVALID_LOGIN_DETAILS',
    MISSING_REQUIRED_FIELDS:'MISSING_REQUIRED_FIELDS',
    INVALID_EMAIL_ADDRESS:'INVALID_EMAIL_ADDRESS',
    EMAIL_ALREADY_EXISTS:'EMAIL_ALREADY_EXISTS',
    INTERNAL_SERVER_ERROR:'INTERNAL_SERVER_ERROR',
    MOVIE_ALREADY_EXISTS:'MOVIE_ALREADY_EXISTS',
    MOVIE_ADD_SUCCESS:'MOVIE_ADD_SUCCESS',
    MOVIE_EDIT_SUCCESS:'MOVIE_EDIT_SUCCESS',
    MOVIE_NOT_FOUND:'MOVIE_NOT_FOUND',
    MOVIE_DELETE_SUCCESS:'MOVIE_DELETE_SUCCESS',
    MOVIE_RATE_SUCCESSFULL:'MOVIE_RATE_SUCCESSFULL'
};